---
layout: null
---
{%- assign formulas = site.data.standalone | where: "lang", "en" | where_exp: "a", "a.url contains '/en/formulas/'" -%}
/* Generated by Jekyll from _data/testes_estatisticos.yml and
 * _data/testes_estatisticos_en.yml (merged by _plugins/paginas_testes.rb):
 * edit there. Same shape as the Portuguese /testes-estatisticos/dados.js. */
window.CATALOGO = {{ site.data.catalogo_en | jsonify }};
window.CATALOGO.formulas = {{ formulas | jsonify }};
window.CATALOGO.formulaBase = "/en/formulas/";
