# Traduções das páginas de fórmulas. Ordem de dl/labels/smalls = ordem na página PT.
X_HINT = "One value per observation, separated by spaces or commas."
Y_HINT = "In the same order as the x values."
STUDY = "Example: five students studied 1, 2, 3, 4 and 5 hours for an exam and scored 52, 58, 65, 70 and 80."

PAGES = {
 "teorema-bayes": dict(
  en="bayes-theorem", h1="Bayes' Theorem", title="Bayes' Theorem — Interactive", aria="Interactive Bayes' theorem formula",
  desc="Bayes' theorem explained term by term, with a calculator: enter the prior, sensitivity and false positive rate and get the posterior step by step.",
  dl=[("Posterior", "The probability of A given that B happened. It updates the belief about A after observing B."),
      ("Likelihood", "The probability of observing B if A is true. It says how compatible A is with the data B."),
      ("Prior", "The initial belief about A before observing B. It may come from previous knowledge or assumptions."),
      ("Marginal (Evidence)", "The probability of observing B across all scenarios; it normalizes the equation. Computed with the law of total probability: P(B) = P(B|A) · P(A) + P(B|¬A) · P(¬A)")],
  lede="Example: a disease affects 1% of the population. A test detects 95% of sick people, but also comes back positive for 5% of healthy ones. If your test is positive, what is the chance you have the disease? Here A is “having the disease” and B is “testing positive”. Change the values to work out your own case.",
  labels=["Prior <i>P(A)</i> (%)", "Likelihood <i>P(B|A)</i> (%)", "False positive <i>P(B|¬A)</i> (%)"]),
 "probabilidade-condicional": dict(
  en="conditional-probability", h1="Conditional Probability", title="Conditional Probability — Interactive", aria="Interactive conditional probability formula",
  desc="Conditional probability P(A|B) explained term by term, with a calculator that works from counts, step by step.",
  dl=[("Conditional Probability", "The probability of A happening given that B has already happened. It shows how the occurrence of B affects the probability of A."),
      ("Probability of the Intersection", "The probability that both A and B happen. It is the overlap between events A and B."),
      ("Probability of B", "The probability of event B. It normalizes the formula, keeping the conditional probability between 0 and 1.")],
  lede="Example: in a class of 40 students, 25 take English and 10 take both English and Spanish. Picking a student who takes English at random, what is the chance they also take Spanish? Here A is “takes Spanish” and B is “takes English”. Change the values to work out your own case.",
  labels=["Total cases", "Cases of B", "Cases of A and B together"]),
 "teorema-probabilidade-total": dict(
  en="law-of-total-probability", h1="Law of Total Probability", title="Law of Total Probability — Interactive", aria="Interactive law of total probability formula",
  desc="The law of total probability explained term by term, with a scenario calculator, step by step, and Bayes for each scenario.",
  dl=[("Total Probability of B", "The overall probability of event B, taking into account every possible scenario or partition of the sample space."),
      ("Summation", "Adds over all the partitions A₁, A₂, ..., Aₙ, which together form a complete and mutually exclusive partition of the sample space."),
      ("Conditional Probability P(B|Aᵢ)", "The probability of B given that Aᵢ happened. It is the probability of B within each specific scenario Aᵢ."),
      ("Probability of Aᵢ", "The probability of each partition Aᵢ. The events Aᵢ must be mutually exclusive and exhaustive (their union covers the whole sample space).")],
  lede="Example: a factory has three machines that make 50%, 30% and 20% of its parts, with defect rates of 1%, 2% and 3%. What is the chance that a part picked at random is defective? Change the values to work out your own case.",
  labels=["Probability of each scenario <i>P(A<sub>i</sub>)</i> (%)", "Probability of B in each scenario <i>P(B|A<sub>i</sub>)</i> (%)"],
  smalls=["The scenarios must cover every case without overlapping: they add up to 100%.", "In the same order as the scenarios above."]),
 "coeficiente-binomial": dict(
  en="binomial-coefficient", h1="Binomial Coefficient", title="Binomial Coefficient — Interactive", aria="Interactive binomial coefficient formula",
  desc="The binomial coefficient C(n, k) explained term by term, with an exact calculator and a step-by-step cancellation of the factorials.",
  dl=[("Binomial Coefficient", "The number of ways to choose 'k' elements from a set of 'n' elements, regardless of order."),
      ("Total Items (n!)", "The factorial of the total number of items available in the set we are choosing from."),
      ("Items Chosen (k!)", "The factorial of the number of items we want to choose from the full set of 'n'."),
      ("Items Not Chosen ((n-k)!)", "The factorial of the number of items left in the set after choosing 'k' of them.")],
  lede="Example: how many ways are there to pick a committee of 3 people from a group of 10? Change the values to work out your own case.",
  labels=["Total items <i>n</i>", "Items chosen <i>k</i>"]),
 "teorema-chebyshev": dict(
  en="chebyshev-theorem", h1="Chebyshev's Theorem", title="Chebyshev's Theorem — Interactive", aria="Interactive Chebyshev's theorem formula",
  desc="Chebyshev's theorem explained term by term, with a calculator: the minimum share of the data within μ ± kσ, for any distribution.",
  dl=[("Probability (P)", "The probability of an event. In Chebyshev's theorem, it is the probability that the random variable lies a certain distance from the mean."),
      ("Absolute Value |X - μ|", "The distance between the random variable X and its mean μ. The absolute value measures the distance regardless of direction (above or below the mean)."),
      ("Constant k (k)", "A positive real number (k &gt; 0) giving how many standard deviations we are considering. For example, k = 2 means 2 standard deviations from the mean."),
      ("Standard Deviation (σ)", "The standard deviation of the random variable X, which measures how spread out the data are around the mean. It is the square root of the variance."),
      ("One (1)", "The numerator of the fraction that bounds the maximum probability."),
      ("k Squared (k²)", "The denominator of the fraction. The larger k is, the smaller 1/k² gets, meaning values far from the mean are less likely. For example, with k = 2, P(|X - μ| ≥ 2σ) ≤ 1/4 = 0.25: at most 25% of the data lie more than 2 standard deviations from the mean.")],
  lede="Example: salaries at a company have a mean of $3,000 and a standard deviation of $500, but the shape of the distribution is unknown. At minimum, what share of salaries falls between $2,000 and $4,000? Change the values to work out your own case.",
  labels=["Mean <i>μ</i>", "Standard deviation <i>σ</i>", "Standard deviations <i>k</i>"]),
 "distribuicao-bernoulli": dict(
  en="bernoulli-distribution", h1="Bernoulli Distribution", title="Bernoulli Distribution — Interactive", aria="Interactive Bernoulli distribution formula",
  desc="The Bernoulli distribution explained term by term, with a calculator, a chart and a step-by-step P(X = k).",
  dl=[("Probability of k", "The probability of getting exactly 'k' in a single Bernoulli trial, where k can be 0 (failure) or 1 (success)."),
      ("Probability of Success (p^k)", "The probability of success 'p' raised to the power 'k'. When k = 1 it gives p (success); when k = 0 it gives 1."),
      ("Probability of Failure ((1-p)^(1-k))", "The probability of failure (1-p) raised to the power (1-k). When k = 0 it gives (1-p) (failure); when k = 1 it gives 1.")],
  lede="Example: a player scores 75% of their penalty kicks. On one kick, what is the chance they score (k = 1)? Change the values to work out your own case.",
  labels=["Probability of success <i>p</i> (%)", "Outcome <i>k</i> (0 or 1)"]),
 "distribuicao-binomial": dict(
  en="binomial-distribution", h1="Binomial Distribution", title="Binomial Distribution — Interactive", aria="Interactive binomial distribution formula",
  desc="The binomial distribution explained term by term, with a calculator for P(X = k), cumulative probabilities, a chart and step-by-step working.",
  dl=[("Probability of k Successes", "The probability of getting exactly 'k' successes in 'n' independent trials, each with probability 'p' of success."),
      ("Binomial Coefficient", "The number of different ways to choose 'k' successes out of 'n' trials. Computed as C(n, k) = n! / (k! · (n-k)!)."),
      ("Probability of Success (p^k)", "The probability of success 'p' on each trial, raised to the power 'k'. It is the probability that k specific trials are all successes."),
      ("Probability of Failure ((1-p)^(n-k))", "The probability of failure (1-p) raised to the power (n-k). It is the probability of (n-k) failures in the remaining trials.")],
  lede="Example: the same player, who scores 75% of penalty kicks, takes 10. What is the chance they score exactly 8? Change the values to work out your own case.",
  labels=["Trials <i>n</i>", "Probability of success <i>p</i> (%)", "Successes <i>k</i>"]),
 "distribuicao-poisson": dict(
  en="poisson-distribution", h1="Poisson Distribution", title="Poisson Distribution — Interactive", aria="Interactive Poisson distribution formula",
  desc="The Poisson distribution explained term by term, with a calculator for P(X = k), cumulative probabilities, a chart and step-by-step working.",
  dl=[("Probability of k Occurrences", "The probability that the event happens exactly 'k' times in an interval."),
      ("Mean Rate (λ) to the Power k", "Lambda (λ) is the mean rate at which the event occurs. This term scales the rate to the specific number of occurrences 'k'."),
      ("Exponential of the Negative Mean Rate", "Euler's number (e) raised to -λ. This term is the probability of no occurrences, the base of the calculation."),
      ("k Factorial", "The factorial of the number of occurrences 'k'. It normalizes the distribution, accounting for the different ways the 'k' occurrences can be arranged.")],
  lede="Example: a call center receives an average of 4 calls per minute. What is the chance that exactly 6 arrive in a minute? Change the values to work out your own case.",
  labels=["Mean rate <i>λ</i>", "Occurrences <i>k</i>"]),
 "distribuicao-normal": dict(
  en="normal-distribution", h1="Normal (Gaussian) Distribution", title="Normal Distribution — Interactive", aria="Interactive normal distribution formula",
  desc="The normal distribution explained term by term, with a calculator for the density f(x), a chart of the area P(X ≤ x) and step-by-step working.",
  dl=[("Density Function (f(x))", "The relative likelihood that a continuous random variable takes a specific value 'x'."),
      ("Normalizing Coefficient", "This term makes the total area under the curve equal to 1. It is built from the standard deviation (σ) and 2π."),
      ("Exponential Function", "The heart of the distribution, where 'e' is the base of the natural logarithm. The exponent depends on how far 'x' is from the mean (μ), measured in standard deviations (σ).")],
  lede="Example: adult height follows a normal distribution with mean 170 cm and standard deviation 10 cm. What is the density at 185 cm, and what share of people is shorter than that? Change the values to work out your own case.",
  labels=["Mean <i>μ</i>", "Standard deviation <i>σ</i>", "Value <i>x</i>"]),
 "teorema-central-limite": dict(
  en="central-limit-theorem", h1="Central Limit Theorem", title="Central Limit Theorem — Interactive", aria="Interactive central limit theorem formula",
  desc="The central limit theorem explained term by term, with a simulation: the histogram of sample means turns into a bell as n grows.",
  dl=[("Sample Mean (X̄ₙ)", "The mean of a sample of size 'n' drawn from the population. The theorem describes the distribution of these means."),
      ("Is Distributed As (~)", "Means that, as the sample size 'n' grows, the distribution of sample means approaches a normal distribution."),
      ("Normal Distribution (N)", "A continuous, bell-shaped probability distribution defined by its mean and variance."),
      ("Population Mean (μ)", "The mean of the whole population. The distribution of sample means is centered on this value."),
      ("Population Variance (σ²)", "A measure of how spread out the data are across the whole population."),
      ("Sample Size (n)", "The number of observations in each sample. The variance of the distribution of sample means shrinks as 'n' grows.")],
  lede="Example: the waiting time at a bus stop follows an exponential distribution, which is quite skewed, with a mean of 10 minutes. The chart shows the means of 2,000 samples of 30 waits each. Change n to watch the bell form, or fall apart when n is small.",
  labels=["Population mean <i>μ</i>", "Size of each sample <i>n</i>"]),
 "z-score": dict(
  en="z-score", h1="Z-Score", title="Z-Score — Interactive", aria="Interactive z-score formula",
  desc="The z-score explained term by term, with a calculator, step-by-step working and the matching percentile in the normal distribution.",
  dl=[("Z-Score (Z)", "Measures how far a data point is from the mean, in standard deviations. A positive z-score means the point is above the mean; a negative one, below."),
      ("Observed Value (X)", "The specific data point or value you are evaluating."),
      ("Population Mean (μ)", "The mean of all data points in the population the sample was drawn from."),
      ("Population Standard Deviation (σ)", "Measures how spread out the data are in the population. It is the square root of the variance.")],
  lede="Example: on an exam with a mean of 70 and a standard deviation of 8, a student scored 82. How far above the mean are they? Change the values to work out your own case.",
  labels=["Observation <i>X</i>", "Mean <i>μ</i>", "Standard deviation <i>σ</i>"]),
 "t-student": dict(
  en="students-t-test", h1="Student's t-Test", title="Student's t-Test — Interactive", aria="Interactive Student's t-test formula",
  desc="Student's t-test explained term by term, with a calculator for the t statistic, degrees of freedom, p-value and step-by-step working.",
  dl=[("t Statistic", "The test statistic that measures how many standard errors the sample mean is from the hypothesized mean. Used when the population standard deviation is unknown and the sample is small."),
      ("Sample Mean (x̄)", "The mean computed from the sample. It is the estimate of the population parameter based on the observed data."),
      ("Hypothesized Mean (μ₀)", "The value of the mean under the null hypothesis (H₀). It is the value we are testing the population mean against."),
      ("Sample Standard Deviation (s)", "The standard deviation computed from the sample. It estimates the population standard deviation when that is unknown."),
      ("Square Root of n (√n)", "The square root of the sample size. Together with the sample standard deviation, it forms the standard error of the mean (s/√n), which measures how much the sample mean varies.")],
  lede="Example: a machine should fill bags with 500 g. In a sample of 25 bags, the mean was 496 g with a standard deviation of 8 g. Is the machine out of adjustment? Change the values to work out your own case.",
  labels=["Sample mean <i>x̄</i>", "Hypothesized mean <i>μ₀</i>", "Standard deviation <i>s</i>", "Sample size <i>n</i>"]),
 "intervalo-confianca": dict(
  en="confidence-interval", h1="Confidence Interval", title="Confidence Interval — Interactive", aria="Interactive confidence interval formula",
  desc="The confidence interval for a mean explained term by term, with a calculator, critical z value, margin of error and step-by-step working.",
  dl=[("Confidence Interval (CI)", "A range of values that, at a given confidence level (usually 95% or 99%), contains the true population parameter. It expresses the uncertainty in the estimate."),
      ("Sample Mean (x̄)", "The mean computed from the sample. It is the center of the confidence interval and the best estimate of the population parameter."),
      ("Plus or Minus (±)", "Shows that the interval extends both above and below the sample mean, making it symmetric."),
      ("Critical Z Value (z<sub>α/2</sub>)", "The value of the standard normal distribution that matches the chosen confidence level. For 95% confidence, z<sub>α/2</sub> ≈ 1.96; for 99%, z<sub>α/2</sub> ≈ 2.58."),
      ("Standard Deviation (σ)", "The population standard deviation, which the formula assumes is known. When it is estimated from the sample itself, z should be replaced by the critical value of the <a href=\"students-t-test.html\">t distribution</a>."),
      ("Square Root of n (√n)", "The square root of the sample size. In the denominator, it shrinks the margin of error as the sample grows, making the estimate more precise.")],
  lede="Example: a sample of 36 light bulbs lasted 1,200 hours on average. The production's standard deviation is known to be 120 hours. Between which values does the mean life of all bulbs lie, at 95% confidence? Change the values to work out your own case.",
  labels=["Sample mean <i>x̄</i>", "Standard deviation <i>σ</i>", "Sample size <i>n</i>", "Confidence (%)"]),
 "poder-estatistico": dict(
  en="statistical-power", h1="Statistical Power", title="Statistical Power — Interactive", aria="Interactive sample size from power formula",
  desc="Sample size from statistical power explained term by term: a calculator for one- and two-sample t-tests, a power curve and a check with the noncentral t.",
  dl=[("Sample Size (n)", "How many observations each group needs for the test to detect the effect with the requested power. With two groups, the total is twice that."),
      ("Number of Groups (g)", "2 to compare two independent groups, such as treatment and control: each mean carries its own uncertainty, and the variance of the difference doubles. 1 for one sample against a fixed value or for paired data, where the mean of the differences is tested."),
      ("Critical Value (z<sub>α/2</sub>)", "The threshold for rejecting H₀ in a two-sided test at level α. For α = 5%, z<sub>α/2</sub> ≈ 1.96. A smaller α pushes the threshold out and calls for more data."),
      ("Power Quantile (z<sub>β</sub>)", "The standard normal value with β = 1 − power below it. For 80% power, β = 20% and z<sub>β</sub> ≈ 0.84; for 90%, ≈ 1.28. It is the slack that makes the real effect clear the threshold in most samples."),
      ("Squared Effect Size (d²)", "Cohen's d is the difference in means divided by the standard deviation: 0.2 is small, 0.5 medium and 0.8 large. With paired data, use the d of the differences. Because it is squared, halving the effect quadruples the sample.")],
  lede="Example: a trial will compare a treatment with a control and expects a medium difference (Cohen's d = 0.5). How many participants per group are needed to detect it with 80% power at 5% significance? Use g = 2 for two independent groups and g = 1 for one sample or paired data. Change the values to work out your own case.",
  labels=["Effect size <i>d</i>", "Significance <i>α</i> (%)", "Power (%)", "Groups <i>g</i>"],
  values={"d": ("0,5", "0.5")}),
 "qui-quadrado": dict(
  en="chi-square-test", h1="Chi-Square Test (χ²)", title="Chi-Square Test — Interactive", aria="Interactive chi-square test formula",
  desc="The chi-square goodness-of-fit test explained term by term, with a calculator, a table of terms, p-value and step-by-step working.",
  dl=[("Chi-Square (χ²)", "The test statistic. A high value means a large gap between the observed and the expected data."),
      ("Summation", "Adds the result of the calculation over every category or group in your data."),
      ("Squared Difference", "The difference between the observed frequency (Oᵢ) and the expected frequency (Eᵢ), squared so that negative values don't cancel out."),
      ("Expected Frequency (Eᵢ)", "The frequency you would expect in a category if the null hypothesis were true. It normalizes the squared difference.")],
  lede="Example: a die was rolled 60 times and faces 1 to 6 came up 8, 12, 9, 11, 6 and 14 times. Is it fair? Change the values to test your own case.",
  labels=["Observed frequencies <i>O<sub>i</sub></i>", "Expected frequencies <i>E<sub>i</sub></i>"],
  smalls=["One per category, separated by spaces or commas.", "Counts that add up to the same as the observed ones, or proportions that add up to 1."],
  ph=["blank: all categories equally likely"]),
 "cochran-formula": dict(
  en="cochran-formula", h1="Cochran's Formula", title="Cochran's Formula — Interactive", aria="Interactive Cochran's formula",
  desc="Cochran's formula explained term by term, with a calculator for the sample size needed to estimate a proportion, step by step.",
  dl=[("Sample Size (n₀)", "The number of people to include in the sample to get statistically meaningful results, assuming a large or infinite population."),
      ("Squared Z-Score (Z²)", "The critical value of the standard normal distribution for the chosen confidence level. For example, at 95% confidence, Z ≈ 1.96."),
      ("Estimated Proportion (p̂)", "The estimated share of the population with a given characteristic. If unknown, p̂ = 0.5 is used, which maximizes the variance and gives the largest possible sample."),
      ("Complement of the Proportion (q̂)", "Computed as (1 - p̂). It is the estimated share of the population without the characteristic."),
      ("Squared Margin of Error (e²)", "The desired precision, also called sampling error. It is the 'window' around the estimate (e.g. ±5%).")],
  lede="Example: a poll wants to estimate the share of voters who approve of a candidate, at 95% confidence with a margin of error of 5 percentage points. With no prior estimate, p̂ = 50% is used, which gives the largest possible sample. Change the values to work out your own case.",
  labels=["Confidence (%)", "Estimated proportion <i>p̂</i> (%)", "Margin of error <i>e</i> (%)"]),
 "margem-de-erro": dict(
  en="margin-of-error", h1="Margin of Error", title="Margin of Error — Interactive", aria="Interactive margin of error formula",
  desc="The margin of error of a poll explained term by term, with a calculator for proportions, the finite population correction and a simulation of 100 confidence intervals.",
  dl=[("Margin of Error (E)", "How far the sample proportion can be from the population proportion, at the chosen confidence level. It is the \"plus or minus 3 points\" of election polls: half the width of the confidence interval."),
      ("Critical Value (z<sub>α/2</sub>)", "The standard normal value that leaves α/2 in each tail. At 95% confidence, z<sub>α/2</sub> ≈ 1.96; at 99%, ≈ 2.58. More confidence calls for a wider margin."),
      ("Standard Error of the Proportion", "The standard deviation of p̂ across different samples. It peaks at p̂ = 50% and falls with the square root of n: to halve the margin, you need four times the sample."),
      ("Finite Population Correction", "Shrinks the margin when the sample is a large slice of the population N. With 1,000 out of 100,000 (1%), the factor is 0.995 and changes almost nothing, which is why population size matters so little. For a very large population, it equals 1. See also the <a href=\"finite-population-correction.html\">correction applied to the sample size</a>.")],
  lede="Example: a pollster interviewed 1,000 voters in a city of 100,000, and 50% said they would vote for candidate A. What is the margin of error at 95% confidence? Leave the population blank for a very large one. Change the values to work out your own case.",
  labels=["Sample size <i>n</i>", "Observed proportion <i>p̂</i> (%)", "Confidence (%)", "Population <i>N</i>"],
  ph=["optional"]),
 "correcao-populacao-finita": dict(
  en="finite-population-correction", h1="Finite Population Correction", title="Finite Population Correction — Interactive", aria="Interactive finite population correction formula",
  desc="The finite population correction explained term by term, with a calculator that shrinks the sample size, step by step.",
  dl=[("Corrected Sample Size (n)", "The sample size adjusted for populations that are not very large. This correction reduces the required sample size."),
      ("Initial Sample Size (n₀)", "The sample size computed with Cochran's formula (or another), which assumes an infinite population."),
      ("Correction Factor", "The start of the denominator, which adjusts the sample size to the size of the population."),
      ("Initial Sample Minus One (n₀ - 1)", "Part of the correction factor calculation."),
      ("Population Size (N)", "The total number of individuals in the finite population you are studying.")],
  lede="Example: the poll from <a href=\"cochran-formula.html\">Cochran's formula</a> would need 385 voters in a large population. What if the town has only 2,000 voters? Change the values to work out your own case.",
  labels=["Initial sample <i>n₀</i>", "Population size <i>N</i>"]),
 "neyman-allocation": dict(
  en="neyman-allocation", h1="Neyman Allocation", title="Neyman Allocation — Interactive", aria="Interactive Neyman allocation formula",
  desc="Neyman allocation explained term by term, with a calculator that splits the sample across strata and compares it with proportional allocation.",
  dl=[("Sample of Stratum h (nₕ)", "The sample size to draw from a specific stratum 'h'. It is the value the formula computes."),
      ("Total Sample Size (n)", "The total number of individuals in the final sample, adding up the samples of all strata."),
      ("Population of Stratum h (Nₕ)", "The total number of individuals in stratum 'h' of the population."),
      ("Standard Deviation of Stratum h (σₕ)", "The standard deviation of the variable of interest within stratum 'h'. Strata with more variability get a larger sample."),
      ("Weighted Sum (Σ Nₕσₕ)", "The sum of each stratum's population size (Nₕ) times its standard deviation (σₕ), over all strata. It works as a normalizing factor.")],
  lede="Example: a company wants to estimate the average salary by interviewing 200 employees. It has three departments: operations (1,000 people, standard deviation of $300), administration (400 people, $800) and management (100 people, $3,000). How many should be interviewed in each? Change the values to work out your own case.",
  labels=["Total sample <i>n</i>", "Size of each stratum <i>N<sub>h</sub></i>", "Standard deviation of each stratum <i>σ<sub>h</sub></i>"],
  smalls=["One per stratum, separated by spaces or commas.", "In the same order as the strata above."]),
 "covariancia": dict(
  en="covariance", h1="Covariance", title="Covariance — Interactive", aria="Interactive covariance formula",
  desc="Covariance explained term by term, with a calculator that takes lists of x and y, a table of deviations and step-by-step working.",
  dl=[("Covariance", "Measures the linear relationship between two variables. A positive value indicates a direct relationship; a negative one, an inverse relationship."),
      ("Summation", "Adds the products of the deviations over all 'n' observations in the data."),
      ("Deviation of X", "The difference between each value of X (xi) and the mean of X (μx). It shows how far each point is from the mean."),
      ("Deviation of Y", "The difference between each value of Y (yi) and the mean of Y (μy). It shows how far each point is from the mean."),
      ("Number of Observations (n)", "The total number of pairs of observations in the data. It normalizes the sum to give the mean of the products of the deviations.")],
  lede=STUDY + " Do hours and score move together? Change the values to work out your own case.",
  labels=["Values of <i>x</i>", "Values of <i>y</i>"], smalls=[X_HINT, Y_HINT]),
 "coeficiente-pearson": dict(
  en="pearson-correlation", h1="Pearson Correlation Coefficient (r)", title="Pearson Correlation (r) — Interactive", aria="Interactive Pearson correlation formula",
  desc="The Pearson correlation coefficient explained term by term, with a calculator, r², an interpretation of strength and step-by-step working.",
  dl=[("Pearson Coefficient (r)", "Measures the strength and direction of the linear relationship between two variables. It ranges from -1 (perfect negative correlation) to +1 (perfect positive correlation)."),
      ("Covariance of X and Y", "Measures how two variables change together. It is the numerator of the formula."),
      ("Standard Deviation of X", "Measures how spread out the values of X are around their mean."),
      ("Standard Deviation of Y", "Measures how spread out the values of Y are around their mean.")],
  lede=STUDY + " How strong is the relationship between hours and score? Change the values to work out your own case.",
  labels=["Values of <i>x</i>", "Values of <i>y</i>"], smalls=[X_HINT, Y_HINT]),
 "regressao-linear": dict(
  en="linear-regression", h1="Simple Linear Regression", title="Linear Regression — Interactive", aria="Interactive simple linear regression formula",
  desc="Simple linear regression explained term by term, with a calculator for the least-squares line, a prediction and step-by-step working.",
  dl=[("Predicted Value (ŷ)", "The estimated value of the dependent variable (Y) for a given value of the independent variable (x)."),
      ("Intercept (β₀)", "The predicted value of Y when the independent variable (x) is zero. It is where the regression line crosses the Y axis."),
      ("Slope (β₁)", "The change in the predicted value of Y for each one-unit increase in x. It is the slope of the regression line."),
      ("Independent Variable (x)", "The variable used to predict or explain the variation in the dependent variable (Y).")],
  lede=STUDY + " Which line predicts the score from the hours, and what score should someone who studies 4.5 hours expect? Change the values to work out your own case.",
  labels=["Values of <i>x</i>", "Values of <i>y</i>", "Predict for <i>x</i> ="], smalls=[X_HINT, Y_HINT],
  ph=["optional"], values={"x0": ("4,5", "4.5")}),
 "media-harmonica": dict(
  en="harmonic-mean", h1="Harmonic Mean", title="Harmonic Mean — Interactive", aria="Interactive harmonic mean formula",
  desc="The harmonic mean explained term by term, with a calculator, step-by-step working and a comparison with the arithmetic mean.",
  dl=[("Harmonic Mean (H)", "A kind of average suited to sets of rates, such as speeds. It is the number of observations divided by the sum of the reciprocals of each observation."),
      ("Total Number of Observations (n)", "The total count of values or observations in the data."),
      ("Sum of the Reciprocals (Σ 1/xᵢ)", "The sum of the inverse of each value (xᵢ) in the data. The reciprocal of a number is 1 divided by that number.")],
  lede="Example: a car drives from one town to another at 60 km/h and comes back the same way at 40 km/h. What was the average speed of the trip? Change the values to work out your own case.",
  labels=["Values <i>x<sub>i</sub></i>"], smalls=["All positive, separated by spaces or commas."]),
 "formula-quadratica": dict(
  en="quadratic-formula", h1="Quadratic Formula", title="Quadratic Formula — Interactive", aria="Interactive quadratic formula",
  desc="The quadratic formula explained term by term, with a calculator for real or complex roots and step-by-step working.",
  dl=[("Solution (x)", "The roots, or solutions, of a quadratic equation of the form ax² + bx + c = 0."),
      ("Negative of Coefficient 'b'", "The opposite of coefficient 'b', the term that multiplies 'x' in the equation."),
      ("Plus or Minus (±)", "Shows that the formula gives two solutions: one adding the square root of the discriminant and one subtracting it."),
      ("Discriminant (Δ)", "The expression b² − 4ac, called the discriminant (Δ). If Δ &gt; 0, there are two real roots; if Δ = 0, one double root; if Δ &lt; 0, two complex conjugate roots."),
      ("Divisor (2a)", "Twice coefficient 'a', the term that multiplies x². This value normalizes the expression.")],
  lede="Example: solve x² − 5x + 6 = 0, that is, a = 1, b = −5 and c = 6. Change the coefficients to solve your own equation.",
  labels=["Coefficient <i>a</i>", "Coefficient <i>b</i>", "Coefficient <i>c</i>"]),
 "regra-lhopital": dict(
  en="lhopital-rule", h1="L'Hôpital's Rule", title="L'Hôpital's Rule — Interactive", aria="Interactive L'Hôpital's rule formula",
  desc="L'Hôpital's rule explained term by term, with worked examples of 0/0 and ∞/∞ and the common mistake of using it without an indeterminate form.",
  dl=[("Indeterminate Form", "The rule applies when the limit of a fraction f(x)/g(x) gives an indeterminate form, such as 0/0 or ±∞/±∞."),
      ("Limit", "The limit of the new fraction is taken as 'x' approaches the same point 'c'."),
      ("Derivative of the Numerator", "Take the derivative of the original numerator, f(x), which gives f'(x)."),
      ("Derivative of the Denominator", "Take the derivative of the original denominator, g(x), which gives g'(x). Note that this is not the derivative of the quotient.")],
  extra=[
   ("<h2 id=\"ex-title\">Exemplos resolvidos</h2>", "<h2 id=\"ex-title\">Worked examples</h2>"),
   ("<h3>0/0, aplicando a regra duas vezes</h3>", "<h3>0/0, applying the rule twice</h3>"),
   ("<h3>Erro comum: usar a regra sem indeterminação</h3>", "<h3>Common mistake: using the rule without an indeterminate form</h3>"),
   ("<span>Substituir x = 0 dá 0/0, uma forma indeterminada:</span>", "<span>Plugging in x = 0 gives 0/0, an indeterminate form:</span>"),
   ("<span>Derive o numerador e o denominador separadamente:</span>", "<span>Differentiate the numerator and the denominator separately:</span>"),
   ("<span>Ainda dá 0/0 em x = 0. Aplique a regra de novo:</span>", "<span>It is still 0/0 at x = 0. Apply the rule again:</span>"),
   ("<span>Agora a substituição funciona:</span>", "<span>Now plugging in works:</span>"),
   ("<span>Quando x cresce, numerador e denominador vão ao infinito: ∞/∞.</span>", "<span>As x grows, the numerator and the denominator both go to infinity: ∞/∞.</span>"),
   ("<span>Derive cada parte: a derivada de ln x é 1/x, e a de x é 1.</span>", "<span>Differentiate each part: the derivative of ln x is 1/x, and that of x is 1.</span>"),
   ("<span>Com x indo ao infinito, 1/x vai a zero:</span>", "<span>As x goes to infinity, 1/x goes to zero:</span>"),
   ("<span>Aqui a substituição direta já resolve, porque não há indeterminação:</span>", "<span>Here plugging in directly already works, because there is no indeterminate form:</span>"),
   ("<span>Aplicar a regra mesmo assim daria um resultado errado:</span>", "<span>Applying the rule anyway would give a wrong result:</span>"),
   ("<p class=\"calc-note\">A regra só vale para 0/0 ou ∞/∞. Antes de derivar, substitua o ponto e confira se a forma é mesmo indeterminada.</p>",
    "<p class=\"calc-note\">The rule only holds for 0/0 or ∞/∞. Before differentiating, plug in the point and check that the form really is indeterminate.</p>"),
   ("\\text{ ou }", "\\text{ or }"),
  ]),
}

# Índice
CATEGORIES = {
 "Probabilidade": "Probability", "Distribuições": "Distributions", "Inferência": "Inference",
 "Amostragem": "Sampling", "Associação e médias": "Association and means", "Álgebra e cálculo": "Algebra and calculus",
}
BLURBS = {
 "teorema-bayes": "Updates the probability of a hypothesis after seeing evidence.",
 "probabilidade-condicional": "The chance of A when you already know B happened.",
 "teorema-probabilidade-total": "Adds up the probability of B across every scenario of a partition.",
 "coeficiente-binomial": "How many ways there are to choose k items out of n, ignoring order.",
 "teorema-chebyshev": "A bound on the share of data far from the mean, for any distribution.",
 "distribuicao-bernoulli": "A single trial with two outcomes: success or failure.",
 "distribuicao-binomial": "The number of successes in n independent trials.",
 "distribuicao-poisson": "The number of events in an interval, given a mean rate.",
 "distribuicao-normal": "The bell curve defined by its mean and standard deviation.",
 "teorema-central-limite": "Why the sample mean tends to a normal distribution as n grows.",
 "z-score": "How many standard deviations an observation is from the mean.",
 "t-student": "Compares a sample mean with a hypothesized value when σ is unknown.",
 "intervalo-confianca": "A range of plausible values for the population mean.",
 "poder-estatistico": "How many observations a t-test needs to detect an effect.",
 "qui-quadrado": "Measures the gap between observed and expected frequencies.",
 "cochran-formula": "Sample size to estimate a proportion with a given margin of error.",
 "margem-de-erro": "The \"plus or minus\" of a poll, from the sample size.",
 "correcao-populacao-finita": "Shrinks the sample size when the population is small.",
 "neyman-allocation": "Splits the sample across strata by size and variability.",
 "covariancia": "Whether two variables move together, and in which direction.",
 "coeficiente-pearson": "Strength and direction of a linear relationship, from −1 to 1.",
 "regressao-linear": "The line that predicts y from x.",
 "media-harmonica": "The right average for rates and ratios.",
 "formula-quadratica": "The roots of ax² + bx + c = 0.",
 "regra-lhopital": "Resolves indeterminate limits of the form 0/0 or ∞/∞.",
}
INDEX = dict(
 title="Interactive Formulas",
 desc="Statistics and probability formulas explained term by term, with calculators, step-by-step working and charts: Bayes, distributions, tests, sampling and more.",
 h1="Formulas",
 lede="{n} statistics and probability formulas explained term by term. Open one and tap each piece to see what it means.",
 ph="Filter: bayes, sample, normal…", label="Filter formulas", empty="No formula with that name.",
)
